# Generated by Django 3.2.4 on 2021-07-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
